### ISSUE TITLE
Optimize the tile spacing rendering

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1079]
Tile spacing is currently used on images (#897) and gradients (#1078).

Images use transparency/blending for the blank spaces. Thus, an opaque image with tile spacing has to appear in the transparency bin, render last, and not contribute to the depth. This is inefficient.

Gradients issue `discard` instructions, which prevent hardware HiZ and early-Z optimizations.

It would be good to have them rendered more efficiently.
Note: simply generating a primitive instance per tile is not a universal solution, since the tiles can be really small, and if there is a lot of them, we'll just blow our memory capacity/bandwidth.

We could either have a mixed solution with some heuristic, or do a completely separate instanced draw call for such tiled primitive (be it a gradient or an image) with the vertex shader producing actual tiles.

**Comment by nical** [comment]
If anyone wants to experiment with this, the code for decomposing repeated images into separate primitives already exists because of the cases where we can't do that in the image shader, for example in some tiling situations. The implementation is in [decompose_image in frame.rs](https://github.com/servo/webrender/blob/6b9db3d1a39e6f6e9cca2fbe8f49de09c126c722/webrender/src/frame.rs#L712).

This should be mostly a matter of tweaking the heuristic that decides when to do the decomposition which currently is only based on whether the image is repeated and tiled in a given direction at the same time.
It would be good to collect some real world use cases first, though.

**Comment by glennw** [comment]
Related to #2312.

**Comment by nical** [comment]
Inclined to close this now that the brush image stuff landed. tile spacing is still done in the alpha pass but it's not as expensive in the brush image shader as it was, doesn't add cost to other types of images, and it's rare enough that I don't think we'll want to look into that in the foreseeable future.
