### ISSUE TITLE
filter should be defined to establish a containing block for fixed and absolutely positioned elements

### ISSUE THREAD

**Issue by mrobinson** [servo/webrender#1101]
See https://github.com/w3c/fxtf-drafts/issues/11. Currently we only do this for stacking contexts with transformations and iframes. It might be a good idea to move all of this functionality to Servo though, as I'm not sure that Gecko needs it.

**Comment by mrobinson** [comment]
cc @mstange

**Comment by mstange** [comment]
Gecko uses containing blocks internally to figure out where elements are placed and what they scroll with. As soon as it has generated display lists, it forgets about all that information, because the display items know what they're scrolled by and that's all they need to know. So we definitely don't need webrender to know about containing blocks.

**Comment by glennw** [comment]
@mrobinson Sounds like we can close this and perhaps open a similar bug in servo?

**Comment by mrobinson** [comment]
Yep! Closing this in favor of https://github.com/servo/servo/issues/18507.
