### ISSUE TITLE
Textures need to be removed from the device texture map

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1116]
In a [gecko try push](https://treeherder.mozilla.org/logviewer.html#?job_id=90944632&repo=try&lineNumber=24920) I see an assertion error:

`thread '<unnamed>' panicked at 'assertion failed: self.textures.contains_key(&texture_id) == false', C:\builds\moz2_slave\try-w64-d-00000000000000000000\build\src\gfx\webrender\src\device.rs:1121`

Looking at the code it looks like nothing ever removes texture ids from the `self.textures` map. So eventually if a texture id is reused this assertion would fire. On IRC @kvark agreed this seems to be a bug.

**Comment by nical** [comment]
I don't understand how this assertion happens. For a gl texture id (allocated by the driver) to be reused we'd need the original texture to be ```gl.delete_texture```'ed but for that to happen we'd need the Texture instance to be removed from the device.textures map which, as the issue title says, never happens.

When a cached texture id (as in the id allocated by the texture_cache) is reused, the cache_texture_id_map (which is in fact a Vec), already has an entry for it so device.create_texture_ids is not called (the latter is only called when the cached texture id is new (assumed to be equal to the length of cache_texture_id_map)), we just re-init an already existing device texture handle.

This whole thing with a map in the renderer and another one is the device seems overly complicated to me. The vector in renderer supposedly avoids a HashMap lookup but in fact each time we do something with a texture in device.rs we end up doing a HashMap lookup anyway.

Couldn't we cut the mapping between texture cache ids and device texture ids and just have the key we pass to the device be allocated by the texture cache? That way when the texture cache sends TextureUpdateOp::Free(idx) we can just remove the entry from the device texture map (which right now we can't do in a simple way because idx will eventually be reused and when that happens we expect the gl texture to exist in the device and we re-initialize it rather than creating a new one.

**Comment by glennw** [comment]
This assertion no longer exists in the code, since the device no longer has a textures hash map.
