### ISSUE TITLE
2nd window stays blank

### ISSUE THREAD

**Issue by paulrouget** [servo/webrender#1233]
I'm creating 2 windows.

The 2nd window stays white, and flickers from white to black when swap buffer is called.
The 1st window is rendered and updated properly.

I'm not sure if I'm supposed to call make the gl context current at some point or not. `get_gl()` returns the gl context of the proper window. `swap_buffer` is called on the proper window.

If I use make_current, it crashes: `thread 'main' panicked at 'assertion failed: self.programs.contains_key(&program_id) == false', webrender/src/device.rs:1470`

Is it supposed to work?
If so, any special operations I'm supposed to do on `WindowMethods::prepare_for_composite` or on `WindowMethods::present`? What about initialization?

**Comment by paulrouget** [comment]
I'm going to try to figure out what's going on.

It's necessary to call make current:

```
<gw> it should look something like (1) wait for event (2) make current (3) wr.update (4) wr.render (5) window.present
<gw>the GL context needs to be the same for (2) - (5)
```

**Comment by paulrouget** [comment]
Opening 2 windows always end up triggering one of these asserts:

```
debug_assert!(self.programs.contains_key(&program_id) == false);
debug_assert!(self.textures.contains_key(&texture_id) == false);
```

Indeed, `gl.create_program` creates a pid that has already been created earlier.

I use this code to open 2 windows: https://gist.github.com/paulrouget/e131558e298b5cbd33c02a94ad2cc5ec

**Comment by paulrouget** [comment]
@glennw do you mind taking a quick look at this? If you apply the patch mentioned in the previous comment, I think you can reproduce easily.

It only happens if I use `make_current`.

**Comment by glennw** [comment]
@paulrouget OK - I tested this out and got it working by adding one extra line :)

The commit is here - https://github.com/glennw/servo/commit/f09f9c48aaaac3dc1d02603cfa59454b7dcc81c8.

The extra line is here - https://github.com/glennw/servo/commit/f09f9c48aaaac3dc1d02603cfa59454b7dcc81c8 - the context needs to be made current during the Browser::new() call as well - since GL resources are created here.

With that change, I was able to open two windows that draw successfully. The events seemed to be getting dispatched incorrectly - scroll events were sometimes getting dispatched to both windows. But that's probably something unrelated that can be sorted out.

Once you've confirmed this works for you, we can close this bug.

**Comment by paulrouget** [comment]
Thank you! It works.

**Comment by kvark** [comment]
@sotaroikeda you might find this conversation useful for establishing multiple windows with WR ^

**Comment by sotaroikeda** [comment]
@kvark , thanks!
