### ISSUE TITLE
Pixel snapping with a stretch

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1279]
We currently pass a single reference point into the primitive's vertex shader, based on which the snapping offset is computed for the whole primitive. That's not exactly how Gecko/Safari do the snapping. We should be snapping both left and right (correspondingly, top and bottom) of a primitive, potentially even stretching it.

**Comment by Gankro** [comment]
Some relevant tests in gecko:

* layout/reftests/pixel-rounding/border-width-5.html == layout/reftests/pixel-rounding/border-width-10-ref.html
* layout/reftests/pagination/abspos-overflow-01-cols.xhtml == layout/reftests/pagination/abspos-overflow-01-cols.ref.xhtml
* layout/reftests/pagination/dynamic-abspos-overflow-01-cols.xhtml == layout/reftests/pagination/dynamic-abspos-overflow-01-cols.ref.xhtml

All of these have a missing column of pixels on the right, because the width on that pixel is 0.5, which the rasterizer happens to decide means that pixel isn't part of the shape.

**Comment by nical** [comment]
Also, we need the snapping information (the two corners) to be independent of the rect of the primitive, otherwise tiled primitives often render incorrectly (1 pixel band between two tiles of the same image) because each tile get snapped independently. Or perhaps the stretching will prevent this bug?
