### ISSUE TITLE
Using an identity transform vs None for a stacking context produces different rendering

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1304]
Apply the following patch to webrender/examples/scrolling.rs:

```
diff --git a/webrender/examples/scrolling.rs b/webrender/examples/scrolling.rs
index 9abc12e..fac7091 100644
--- a/webrender/examples/scrolling.rs
+++ b/webrender/examples/scrolling.rs
@@ -5,19 +5,17 @@
 extern crate gleam;
 extern crate glutin;
 extern crate webrender;
 extern crate webrender_traits;

 use gleam::gl;
 use std::env;
 use std::path::PathBuf;
-use webrender_traits::{ClipId, ColorF, DeviceUintSize, Epoch, LayoutPoint, LayoutRect};
-use webrender_traits::{LayoutSize, PipelineId, ScrollEventPhase, ScrollLocation, TransformStyle};
-use webrender_traits::WorldPoint;
+use webrender_traits::*;

 struct Notifier {
     window_proxy: glutin::WindowProxy,
 }

 impl Notifier {
     fn new(window_proxy: glutin::WindowProxy) -> Notifier {
         Notifier {
@@ -171,16 +169,43 @@ fn main() {
         // corner of the nested scrollframe content, which can be scrolled into
         // view by the user
         let clip = builder.push_clip_region(&(250, 350).to(300, 400), vec![], None);
         builder.push_rect((250, 350).to(300, 400),
                           clip,
                           ColorF::new(0.0, 1.0, 1.0, 1.0));
         builder.pop_clip_id(); // nested_clip_id

+        builder.push_stacking_context(webrender_traits::ScrollPolicy::Scrollable,
+                                      (10,10).to(100,100),
+/* change this to None --> */         Some(PropertyBinding::Value(LayoutTransform::identity())),
+                                      TransformStyle::Flat,
+                                      None,
+                                      webrender_traits::MixBlendMode::Normal,
+                                      vec![FilterOp::Opacity(PropertyBinding::Value(0.5))]);
+
+        builder.push_clip_id(nested_clip_id);
+        builder.push_stacking_context(webrender_traits::ScrollPolicy::Scrollable,
+                                      (10,100).to(40,130),
+                                      Some(PropertyBinding::Value(LayoutTransform::create_translation(10.0, 40.0, 0.0))),
+                                      TransformStyle::Flat,
+                                      None,
+                                      webrender_traits::MixBlendMode::Normal,
+                                      Vec::new());
+        { // this is the content for it - a red 10x10 square
+            let clip = builder.push_clip_region(&(0, 0).to(30, 30), vec![], None);
+            builder.push_rect((0,0).to(30,30),
+                              clip,
+                              ColorF::new(1.0, 0.0, 0.0, 1.0));
+        }
+        builder.pop_stacking_context();
+        builder.pop_clip_id(); // nested_clip_id
+
+        builder.pop_stacking_context(); // opacity 0.5 context
+
         builder.pop_clip_id(); // clip_id
         builder.pop_stacking_context();
     }

     builder.pop_stacking_context();

     api.set_display_list(
         Some(root_background_color),
```

and run the example. Note the position of dark-red square (really a red square with opacity 0.5). Now change the line that says `Some(PropertyBinding::Value(LayoutTransform::identity()))` to `None` (the line is indicated with a comment). Run the example and note the position of the dark-red square.

I would expect the position to to be the same in both cases, but it is not. It's not clear to me why, since an identity transform should behave the same as not setting a transform at all. It's certainly reasonable to expect a performance difference in the two, but a visual difference doesn't seem right.

This appears to be the cause behind a gecko reftest failure with WR when APZ is enabled. I'm tracking this in [bug 1368551](https://bugzilla.mozilla.org/show_bug.cgi?id=1368551). Also related is [bug 1345577](https://bugzilla.mozilla.org/show_bug.cgi?id=1345577).

/cc @mrobinson

**Comment by mrobinson** [comment]
The issue here is that the code is pushing a "Clip" that lives outside of the reference frame. I see now that the scrolling documentation is missing some important information about how positioning is affected by new reference frames. In short:

- Stacking contexts with transformations create reference frames. Reference frames are new coordinate systems for scrolling and fixed positioning. This is a result of how these concepts are defined by the CSS spec.
- Reference frames live as scrolling tree nodes.
- 'Clip' is also used to implement scrolling, so the current clip id is used to position items as well.
- In this case, the clip, which was created outside of the current reference frame of the rectangle, will affect the position of the rectangle.

I think there are two things we should do:
- Understand why Gecko is repushing an ancestor clip. If the reference frame is created as a child of the clip, you shouldn't need to push the clip again, since it is already part of the hierarchy.
- Fix the API to fully separate scrolling and clipping. I've been avoiding doing this since it's a large change and I wanted to avoid causing too much havoc. I think it's gotten to the point though, where the evolution of the API has left it in a very confusing place. It's probably a good idea to prioritize fixing the API. This means having one type for scrolling and a separate type for clipping.

**Comment by staktrace** [comment]
For the record, we discussed this on IRC. The end result of the discussion was that we should try to separate the CSS-specified transform from the other synthetic transforms in gecko, and only pass on the CSS-specified transform to webrender. Otherwise we risk creating new reference frames in unexpected places.

Also,

> Understand why Gecko is repushing an ancestor clip. If the reference frame is created as a 
> child of the clip, you shouldn't need to push the clip again, since it is already part of the 
> hierarchy.

this was a misunderstanding, since Gecko doesn't repush an ancestor clip; the clip in question is popped and repushed in a "sibling" part of the tree.

> Fix the API to fully separate scrolling and clipping.

And this isn't really a problem in Gecko since the bindings.rs wrapper already makes the distinction between these two fairly clear (it exposed two separate APIs - one for clipping and one for scrolling).

**Comment by mrobinson** [comment]
@staktrace I think this one can be closed?

**Comment by staktrace** [comment]
@mrobinson I was thinking about this some more and I still feel that it's a bit of a footgun that a `None` transform produces a different result than an identity transform. I feel like it might be better to make this a bit more explicit in the API by adding a `is_reference_frame` bool argument to `push_stacking_context`. The caller can specify if they want that stacking context to be treated as a reference frame or not, rather than overloading the transform to imply that. That way for a given value of `is_reference_frame` passing a `None` transform or an identity transform would produce the same result. WDYT?

**Comment by mrobinson** [comment]
@staktrace One thing I've been considering,along a similar line is to explicitly expose reference frames to the API. Instead of pushing a stacking context with a transform, you would define a reference frame with a transformation and then push the stacking context as a child. This would also allow clients to handle fixed positioning by assigning stacking contexts the clip id of the reference frame instead of specifying Fixed versus Scrollable as an argument to the stacking context itself.

**Comment by staktrace** [comment]
@mrobinson That sounds like a good idea, I'd be ok with that change.

**Comment by glennw** [comment]
I like this idea too.

**Comment by mrobinson** [comment]
Going to close this in favor of #1443.
