### ISSUE TITLE
Rust panic in Frame::flatten_items

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#1345]
We're seeing some Firefox crashes in the wild and in automation with an expect_failed panic in Frame::flatten_items. We don't have steps to reproduce though, so I'm filing this just to track the problem on the webrender side, or if anybody spots any problems via code inspection.

Relevant bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1344190
https://bugzilla.mozilla.org/show_bug.cgi?id=1368162
https://bugzilla.mozilla.org/show_bug.cgi?id=1370364

**Comment by kvark** [comment]
The expectations seem to fail in different places, which is worrisome:
  - some fail with "no entry found for key", which happens if you try to work with a `HashMap` element by key without safely checking for it. I haven't found yet the exact hashmap in question and the spot it fails.
  - some fail with "No display list?!" when flattening a rectangle display item and looking up the pipeline

**Comment by glennw** [comment]
@staktrace Still relevant?

**Comment by staktrace** [comment]
No I think we haven't seen this in a while. At least I haven't seen any intermittent failures with this recently. We can close this for now.
