### ISSUE TITLE
PBO-based texture updates

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1433]
We already have basic support for PBO for the means of GPU resource cache updates. We should consider also doing it for texture updates.

Roughly, what we can do is:
  - having a persistently-mapped PBO containing all the texture updates per frame to be written by the `RenderBackend` (or, more specifically, `TextureCache`).
  - the `TextureUpdateOp::Update` would just specify the slice of that PBO, so that the `Renderer` just issues a copy into the target texture

cc @jrmuizel @nical @glennw

**Comment by JerryShih** [comment]
@kvark 
If we try to create a PBO and copy the image content into that at TextureCache, which gl context should we use in TextureCache? Since render_backend and render are at different threads, the gl context can't be used at the same time between these threads.
Are you try to create an additional context in TextureCache and share the PBO to render?

**Comment by glennw** [comment]
This is implemented as part of https://github.com/servo/webrender/pull/1572.

**Comment by glennw** [comment]
This happened.
