### ISSUE TITLE
Text glyph pixel snapping

### ISSUE THREAD

**Issue by kvark** [servo/webrender#1451]
Apparently, the fix in #1441 doesn't cut it (see https://github.com/servo/webrender/pull/1441#issuecomment-312922649).

**Comment by jrmuizel** [comment]
I don't think we ever want to snap glyph bitmaps. We should either be re-rasterizing with the transform applied or just transforming a greyscale bitmap without any snapping applied.

**Comment by glennw** [comment]
The snapping is so that we don't bilinear sample on glyphs that have fractional positions (either due to the text layout itself, or the parent stacking context positions). We need to do this to avoid blurry text. This is separate from transformed text, which should not be snapped at all (which is true for all transformed primitives).
