### ISSUE TITLE
CSS filter does not apply on inline elements

### ISSUE THREAD

**Issue by stshine** [servo/webrender#1468]
Testcase:

```html
<!DOCTYPE html>
<html>
    <head>
        <style>
         span {
             filter: blur(10px);
         }
        </style>
    </head>
    <body>
        <span>Foobar</span>
    </body>
</html>
```

Screenshot:
![2017-07-12-080826_1024x740_scrot](https://user-images.githubusercontent.com/1694478/28096180-56f87b66-66d9-11e7-84e6-d1dc0e3dfe5c.png)

This happens because currently we only support filter on `PushStackingContextDisplayItem` but according to CSS spec filter can be applied on arbitrary element.

**Comment by stshine** [comment]
cc @glennw @mrobinson @nical 

I would love to know the solution to this, because according to SVG spec, a transform, a filter, a mask and a mix blend can be applied to any SVG item or a group of them.

**Comment by glennw** [comment]
In CSS, the presence of a filter should establish a stacking context (see https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) which is why we pass filters via ```PushStackingContextDisplayItem```. So this sounds more like an issue with how Servo is doing layout / DL building, I think.

Having said that, applying a mix-blend to arbitrary SVG items etc does sound like it fits in quite well with something we've been discussing recently - adding support for a DL item that groups items and applies some kind of effect / filter / shadow on them.

**Comment by stshine** [comment]
@glennw Oh, missed that part of spec, sorry.

That sounds great! Would love to know your decision about it :)
