### ISSUE TITLE
WebRender has a bad time with https://jrmuizel.github.io/perf-tests/moving-balls.html

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1501]
Profiling servo running this test case shows about 50% of the time in WebRender. The rendering is also incorrect (the solid colors leak out of the borders)

**Comment by glennw** [comment]
Wow, of the 33ms spent in the backend thread, 20ms of that is DL deserialization and processing :(

**Comment by kvark** [comment]
Sounds like @Gankro should be ~~accused~~ involved

**Comment by jrmuizel** [comment]
https://github.com/rust-lang/rust/issues/31681 should help here.

**Comment by glennw** [comment]
This looks correct visually now, but the CPU performance is still a problem. Needs more investigation.

**Comment by kvark** [comment]
I took some measurements. CPU backend time is 50ms. Although, 2/3 of that appears to be spent in just waiting for messages (`pthread_cond_wait`). The rest is mostly spent on scene building.

On the CPU compositor time, GPU cache is only taking 3%, less then the Intel driver spent querying it's own extensions on each draw call (d'oh).

Is it possible for Gecko to use the dynamic transform properties here, avoiding the frame building cost?

**Comment by jrmuizel** [comment]
Here's my profile:
https://perfht.ml/2H2fPnn

The biggest problem is style, but the render backend is spending 74ms moving memory around.

**Comment by kvark** [comment]
As @jrmuizel mentioned, we are also spending 18% of time allocating the space in our texture atlas. This time may be saved once we start re-using the clip masks between items (as mentioned by @glennw  in https://github.com/servo/webrender/pull/2626#issue-179834278), since a lot of the 2294 clips look similar:
![clips](https://user-images.githubusercontent.com/107301/38443529-003c8fa6-39ba-11e8-9392-2d374031dbf3.png)

**Comment by gw3583** [comment]
This runs at a reasonable kind of frame rate given the content for me now.
