### ISSUE TITLE
High gpu time on http://github.com when not signed in

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1571]
STR:
- Turn on layers-free, webrendest, and profiling in Gecko
- Scroll down to the large orange blue and purple circles containing numbers.
- The GPU time goes up to 53ms

**Comment by jrmuizel** [comment]
The circles are done with a large border radius. Does the border radius code perhaps not scale well to large sizes?

**Comment by glennw** [comment]
It's possible. Once I finish up the texture cache refactoring I'm working on (today, hopefully!) I'll be spending some time on GPU profiling an optimization, since we're no longer CPU bottlenecked on most pages. I'll look into this issue as part of that.

**Comment by glennw** [comment]
Ah, I see the cause.

The border radii are fine - but those circles have some box shadows where the parameters have a blur radius of 50px. That size of blur radius along with the size of the shadow rect plus the border radius on them are causing issues in the box shadow blur shader.

It should be relatively simple to fix. I'll add this issue to my list of GPU things to fix up over the next week or two.

**Comment by glennw** [comment]
Upon further investigation, the issue is that the box-shadow shader performance goes off a cliff when there is (a) a large border radius and (b) a large shadow area, due to https://github.com/servo/webrender/blob/27f3d14a7667ef50f41ab70a98689051d515cf6d/webrender/res/cs_box_shadow.glsl#L130.

We'll need a different technique to handle these styles of box shadows.
