### ISSUE TITLE
Scrolling discussion

### ISSUE THREAD

**Issue by trishume** [servo/webrender#1612]
Hi, I'm looking into building a simple UI framework with Webrender, and I'm confused by how scrolling works. This issue is basically just to ask why the design is the way it is, and propose an alternative.

Basically I'm wondering why scrolling is Webrender's responsibility. I get that it made total sense before the property animation infrastructure existed. 

My alternative proposal is that the scrolling logic could be moved out into a separate crate that just animates the viewport property of stacking contexts. Scroll bars would also be rendered as stacking contexts with transforms and opacity animated via properties. This would make Webrender simpler and also allow UI frameworks that use Webrender to customize the appearance of scrollbars, and also tie other animations to scrolling.

At the moment there is no good way to draw custom scrollbars (not that I know how to enable the rendering of scrollbars, I just assume it exists somewhere) because a scroll generates a scroll frame immediately so also animating a property requires redundantly generating another frame.

On a mostly unrelated but somewhat related note, that I can easily split into a separate issue: the scroll bouncing logic needs a lot of work. It doesn't feel nice, and there is currently no way to distinguish between scroll events that should rubber-band (trackpads, magic mice) and scrolls that shouldn't (wheels). I might work on this myself, at least for replicating macOS, but it would be handy to know if it should be done in a separate library using animation, or within Webrender.

cc @pcwalton @glennw

**Comment by jrmuizel** [comment]
I believe your plan basically matches what we plan to do with Gecko and Webrender. @staktrace can probably fill in the details.

**Comment by staktrace** [comment]
Yeah, what you're describing is similar to what Gecko is doing. The scrolling implementation built in to WebRender is insufficient for web compat and so it would need significant changes to use it in Gecko. Instead we decide to reuse our existing C++ code for scrolling, which basically computes the transforms needed for the scrollbars and content, and sends those in to WebRender. Gecko already draws scrollbars using display items, and we set an animated transform property on those stacking contexts so that we can reposition it based on the scroll offset. We also use the `scroll_node_with_id` API to scroll content instead of passing raw input events to WebRender. Since Gecko is relying on this API surface you can reasonably expect it to continue working and not break.

> At the moment there is no good way to draw custom scrollbars (not that I know how to enable the 
> rendering of scrollbars, I just assume it exists somewhere) 

I don't believe WR has a way to render scrollbars at all right now. At least it didn't last time I checked.

> the scroll bouncing logic needs a lot of work. It doesn't feel nice,

I agree with this. And I concur that it should moved into a separate library. The scroll functionality will likely grow to be quite significant and I think it would be better to extract it from WebRender proper.

**Comment by trishume** [comment]
@staktrace cool, thanks for the info.

If Gecko draws its own scroll bars, how does it use the `scroll_node_with_id` API? Doesn't that immediately start rendering a scroll frame, and then you have to submit a new frame to update the scroll bar transforms? Thus rendering two frames when you should only be rendering one.

**Comment by staktrace** [comment]
@trishume There is a RendererOption to disable rendering on scroll which we set from Gecko. So that way we are able to set all transforms and animation updates we need, and then we trigger a render after everything is in place. For Gecko it's not just scrollbars either - we can be scrolling multiple scrollframes at the same time so it's important that we be able to call `scroll_node_with_id` on all them before we try to render anything.

http://searchfox.org/mozilla-central/rev/18c16ebf818abb86805ce08a6e537e4cd826f044/gfx/webrender/src/render_backend.rs#296
http://searchfox.org/mozilla-central/rev/18c16ebf818abb86805ce08a6e537e4cd826f044/gfx/webrender_bindings/src/bindings.rs#598

**Comment by nical** [comment]
Looks like there isn't any concrete plan here. The issue of rendering two frames is solved with the transaction based API. Let's close.
