### ISSUE TITLE
Add a fast path for clips with uniform radii.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#1661]
The clipping shader currently evaluates an ellipse, since the x/y radii of a rounded rect can be different. 

The ellipse evaluation is *much* slower than evaluating a clip against a circle, and elliptical clips are actually very rare in practice.

We should add a fast path clip mask shader that is used when the radii are equal that just evaluates the SDF of a circle.

**Comment by j3parker** [comment]
The ellipse shader code handles circles in the easy/fast way (because the SDF impl for ellipses doesn't work for that special case) here, currently: https://github.com/servo/webrender/blob/6a7b5381b21805f4e3a15cda3bbe8466bc916485/webrender/res/ellipse.glsl#L58-L67

Is the idea in this issue to create a separate fragment shader that only has that path? (Presumably with some `#ifdef`s to cut out the ellipse code.)

If so: when would we decide to use it? I see two options (I'm looking at WebRender for the first time, excuse me if this is way off the mark :) )

1. When [`target.clip_batcher.rectangles`](https://github.com/servo/webrender/blob/d741f472dd3d6c3441646f7bf4e714c71bea39b7/webrender/src/renderer.rs#L2994) is only composed of "nice" rectangles
2. Split the current `rectangles` batch into two batches: one for "nice" and one for "not nice"  rectangles

("nice": all corners use circles)

**Comment by j3parker** [comment]
Hm, total list of shaders using the shared ellipse code:

* `ps_clip_rectangle`
* `brush_mask`
* `cs_clip_rectangle`

**Comment by glennw** [comment]
That's the basic idea, yep!

Although, the clipping code is undergoing quite a lot of changes right now, so it's perhaps not the best time to work on this task.

One step towards this task that would be super useful is to create a wrench test case that does only require circle clips, locally replace the ellipse code by a shader that only does the circle clip, and measure the performance difference. It may be that there's minimal performance gain from this anyway, in which case it won't be pursuing.

In terms of an actual implementation, I'm hoping to have the major clip changes done in the next 2-3 weeks, which would then be a good time to work on this. Thanks!

**Comment by j3parker** [comment]
Alright, sounds good. I'll give the wrench test idea a go tomorrow and report back.

**Comment by gw3583** [comment]
I did some profiling and there's no noticeable performance improvement when modifying the clip mask shader to assume only circular radii (@pcwalton did land some changes to make the ellipse evaluation use far fewer instructions, so it may be explained by this).
