### ISSUE TITLE
Gecko's gmail display list consumes 8ms of cpu time

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1731]
Here's a yaml file: https://jrmuizel.github.io/webrender/gmail.zip
Here's a corresponding bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1401574

**Comment by glennw** [comment]
When I run that, I get a panic - unable to open ```gmail/res/1505931602-font-53.ttf``` which isn't in the zip file. Do you have those locally or is there a wrench bug in saving them? If not, I'll just hack up some local fonts in place.

**Comment by glennw** [comment]
This test case uses around 3.8ms on my machine - confirmed with @jrmuizel that that is actually the amount of time seen on his mac too.

Initial profile shows that the vast majority of the time is spend handling the clips setup in the clip-scroll tree.

This test case does have quite a few clip nodes (well, a lot) - and there is probably quite a bit of redundancy there. Having said that, it's still much slower in WR than it should be for that number of clips.

I suspect I know the issue here, and it happens to be exactly what I am working on fixing right now, coincidentally. When we build the clip stack for each primitive, we cache the clip stack for the most recent clip node ID. This works OK most of the time, but cases like this can easily break it. I'm working on some changes to do that clip stack calculation once per clip node, when the tree is updated at the start of the frame. This will be a performance win in general, and also ensure that performance of building that clip stack is not susceptible to the shape of the clip-scroll tree.

**Comment by glennw** [comment]
There is ~80% of the time spent building the scene, and only 20% spent doing the frame render. This is highly unusual compared to most profiles I've seen. I'm going to spend some time looking into the display list and see where it's spending all the time.

**Comment by glennw** [comment]
Hmmm, if this ```perf``` profile is correct, we're spending around half the entire CPU time in serde deserializing things. Now to find out why...

**Comment by glennw** [comment]
Ah, I think I see the main problem. There are two display lists in the scene. The second one seems to have a huge number of (hopefully redundant) clips defined.

For example, below is a *small segment* of what the DL looks like in the WR debugger. That part repeats for dozens of pages. So we have hundreds (thousands?) of clips being defined. That's putting a big load on the serde deserialize code, as well as the clip stack handling code (which needs work, as I mentioned above).

I'm not sure how easy it is to track down which items in the DL are providing all those clips. This is probably a worthwhile time for me to expand the debug display of the DL in the web debugger so we can see exactly what all those items are.

On the plus side, the performance isn't actually that bad, given the structure of the DL :)

```
 scroll_frame
clip
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
clip
rectangle
```

**Comment by jrmuizel** [comment]
I have a new trace with https://bugzilla.mozilla.org/show_bug.cgi?id=1403697 applied. This new trace should not have the clip per rectangle problem seen above. I get 2.4ms of CPU time in the backend with this trace.

https://jrmuizel.github.io/webrender/gmail-reduced-clip.zip

**Comment by jrmuizel** [comment]
However, when running the page directly in Gecko the CPU time in the backend is more like 11ms so we'll need to figure out what's happening there.

**Comment by glennw** [comment]
I'll re-profile in both cases once I finish up the work on optimizing how WR builds clip chains internally, since I hope this will have a significant effect.

**Comment by jrmuizel** [comment]
So running with -r to rebuild the display list ups the time to 6.8ms this is closer to matching what we see in Gecko.

**Comment by glennw** [comment]
Two things immediately stand out - and they are related, so fixing one may help fix the other.

![profile](https://user-images.githubusercontent.com/2350882/30942849-9b3ca704-a430-11e7-8792-8e392a526614.png)

Sorting the profile results by ```self``` time, the top five functions account for ~47% of the total CPU time. These are all in our DL deserialization code (or serde itself). The top function, memcpy, is mostly allocated to callers from serde too.

The DL size is 0.59 MB - this is quite high, but it still feels like there is something very wrong for the deserialization of 600 kB to take that long. I suspect we're either using the DL deserialization badly (i.e. perhaps we are deserializing the same thing many times?) or there is some serious code-gen issue with how we're using serde? @Gankro would you be able to do some profiling and see what is going on here? (you'll need to use the -r option above so that the DL gets replayed every frame). My gut reaction is that the time to deserialize 600 kB of data on a reasonably modern i7 CPU should be almost negligible, but it doesn't seem that's the case here.

![profile2](https://user-images.githubusercontent.com/2350882/30942863-aeea3456-a430-11e7-93c4-9a6b41f85c6a.png)

The second possible issue is that the DL contains 2366 primitives, but only 382 are actually visible. Although WR is reasonably efficient at culling non-visible items, it still has to pay the deserialization overhead, and build the clip-scroll tree before it can work out which items are visible. In a normal scene, I think Gecko normally has around half the items in the DL being visible, so this seems like quite an interesting case to investigate and see where the invisible primitives are coming from... @jrmuizel Is that something that is easy to look at from the Gecko side? If not I can try to add some extra debugging infrastructure in WR to help determine where the non-visible items are...

**Comment by Gankro** [comment]
Rust's codegen is quite bad on serde (specifically it's bad for large enums because of all the memcopies), as jrmuizel has investigated previously.

**Comment by glennw** [comment]
![profile3](https://user-images.githubusercontent.com/2350882/30943859-4006c494-a437-11e7-995e-b7bc30e2d456.png)

**Comment by glennw** [comment]
(mostly just recording an IRC discussion here with @Gankro for others).

The left box is ```dl_iter::next()``` and most of the time in the 2nd box is time in serde.

I'm going to keep working on other performance areas in the meantime, but we are going to need to come up with a solution that improves the DL processing time. Not sure what that would look like right now.

**Comment by glennw** [comment]
On the plus side, most of the other large-ish boxes on the right hand side are related to dealing with clip sources and clip nodes in the clip-scroll tree, which is what I'm working on improving now. So we should see some reasonable wins from that.

**Comment by jrmuizel** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1403746 on the serialization stuff. Maybe @Gankro can look hooking up -Z enable-noalias tomorrow.

I'll take a look at primitive visibility on the Gecko side to see what's going on. What's the definition of visibility that WebRender is using?

**Comment by glennw** [comment]
Broadly speaking, it's considered visible if all of the following are true:

(a) the primitive screen space bounding rect intersects the screen viewport.
(b) the primitive screen space bounding rect is not clipped out by the screen space bounding rect of any owning clip nodes.
(c) the primitive is not culled out by the ```backface``` flag on the owning stacking context.
(d) the owning stacking context is visible (i.e. not opacity(0).
(e) the primitive alpha is > 0.

I think that covers 99% of the cases we cull items out.

**Comment by jrmuizel** [comment]
Is it possible to get a breakdown of how many primitives fail each test? I ran some numbers on a captured gmail display list and I get something like:
Items: 2316 visible: 913 clipped: 1482 visible and not clipped: 829

**Comment by jrmuizel** [comment]
When I view gmail-reduced-clip I get 716 visible primitives. @glennw is the whole area not visible on your screen?

**Comment by metajack** [comment]
cc @metajack

**Comment by glennw** [comment]
As an update, this test file is now taking 6ms CPU time for me, and 3.5ms GPU time. The CPU time isn't too bad given the huge number of individual clips in this file. @jrmuizel is there still work ongoing in Gecko related to this?

**Comment by Gankro** [comment]
Have you tried it on the latest Rust nightly? Eddyb's enum layout optimizations just landed, might have improved how much we memcopy.

**Comment by gw3583** [comment]
@jrmuizel I think this will probably have been fixed by the recent changes to remove redundant clip nodes in gecko?

**Comment by jrmuizel** [comment]
I suspect so.
