### ISSUE TITLE
Rounded border rendering quality issues

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1750]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402954

\>> [Testcase](https://bug1402954.bmoattachments.org/attachment.cgi?id=8911952) <<

Some rounded borders, for example the one used for the URL bar in the Firefox UI, look jagged and not very round.

There are two major problems:
 1. The curved part of the border doesn't connect smoothly to the straight part of the border. There is a pixel at the connection point which doesn't have full opacity.
 2. The anti-aliasing in general is very crude. The shape looks like it's built out of two or three straight lines per corner, and doesn't look like a round curve.

<img width="680" alt="webrender-rounded-border-comparison" src="https://user-images.githubusercontent.com/961291/30827639-c8fd042e-a208-11e7-84a7-7d96eb781995.png">

**Comment by pcwalton** [comment]
This was a concern that was always somewhat on my mind.

The correct way to do antialiasing is to calculate the area of the arc that covers the pixel square. (Pathfinder 2 ECAA does this using Green's Theorem, approximating parabolic curves with 1-pixel-wide lines as a cheat to improve performance.) I believe that WebRender simply calculates the distance to the edge of the arc. This is an approximation that is valid in 1D (because distance times a constant height equals the area) but not in 2D.

I think it'd be doable to use Green's Theorem for this as well -- I believe clipping the arc in the fragment shader is straightforward with some simple trigonometry -- but there's the question as to whether we need to do that or whether we can get away with a cruder approximation. For instance, we could supersample 4 times in the fragment shader, and that would probably look better than what we have right now.

**Comment by nical** [comment]
Other than precision issues of the approximation, it looks like the border is biased towards the outside (maybe by half a pixel). I haven't delved into this shader yet but I wouldn't be surprised that there is a half-pixel offset somewhere that is extraneous or omitted.

![wr-border](https://user-images.githubusercontent.com/264854/31086444-1f710d50-a79a-11e7-8360-a6601d3e0afb.png)

**Comment by nical** [comment]
I believe this is caused by mismatch between the positions being specified in a coordinate system that is snapped to the _corners_ of the pixels, while the distance should be sampled from the point of view of the _center_ of the pixels. I have a fix that makes the borders look good but I am not 100% certain that it is strictly correct (not sure yet that it is the best place to compensate for that half-px offset).
