### ISSUE TITLE
 Chrome repaints cause rebuilds of the entire browser scene

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1781]
For example: Today I get 22ms of cpu time per frame (this is without some of the coming clipping improvements) when a throbber on another tab is spinning with gmail open in the foreground.

https://bugzilla.mozilla.org/show_bug.cgi?id=1404477

**Comment by glennw** [comment]
Clearly this shouldn't be taking 22ms, and we need to profile / fix that. But I do think the right long term fix is to consider using the document API to have a separate document for the chrome vs. the content. Not only would that work around issues like this - we could potentially use the hardware APIs to only composite the chrome rect in situations like this, as a further saving. Does that sound right to you @kvark ?

**Comment by kvark** [comment]
@glennw yes, that's pretty much the conclusion we got from talks with you and Jeff. Biggest question is how to get from the current scheme in Gecko (where the document is just a separate pipeline/iframe) to a completely independent document.

**Comment by staktrace** [comment]
Is it possible for one document to embed another, the way one pipeline can embed another one using push_iframe? If so this change should be pretty easy on the gecko side.

**Comment by kvark** [comment]
@staktrace the whole point of documents is to have independent workloads for both render backend and renderer. Having one inside of another would only be possible if we bake it into a rendertarget, like what the `frame_output` example does. But this is certainly not what Gecko needs.

And since we are touched this issue - the support for documents on `Renderer` side is done, so I believe WR is ready for this change on Gecko side to be done, assuming Gecko team manages to move the content iframe out of the chrome.

Closing the issue for the work left is on Gecko side, tracked separately. If there is any more fixes to be done here, we'll open separate issues and ideally link to this one.

**Comment by staktrace** [comment]
I don't really understand how the Gecko side is supposed to work if we can't put one document inside another. On the gecko side the web content is embedded inside the chrome content in that there is stuff from the chrome document both "above" and "below" the web content document.

**Comment by kvark** [comment]
@staktrace what does putting the content inside the chrome pipeline tree give you anyway?
You could have the following documents:
  1. Top part of the chrome, with a designated rectangle area
  2. Bottom part of the chrome (status bar) with a designated area
  3. Content part, again covering a sub-rectangle of the full screen
  4. Rounded corners - a transparent document covering full screen

These can be intersecting, there is an API to order them around by assigning a layer ID.

**Comment by staktrace** [comment]
Just to be clear - when I said "above" and "below" I meant in z-order. Stuff from the chrome (e.g. doorhangers) can overlap the content area. But I guess if documents can overlap (which is what it sounds like you're describing) then maybe we can make it work.
