### ISSUE TITLE
IdNamespace is unique only within webrender instance

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#1794]
IdNamespace allocation is managed within webrender instance . Therefore there could be a case that different RenderApi could have same namespace_id between different webrender instances.

It causes the problem like [Bug 1405241](https://bugzilla.mozilla.org/show_bug.cgi?id=1405241) on gecko since gecko assumes unique IdNamespace even between different webrender instances.

I am not sure if the problem should be addressed gecko side or webrender side.

**Comment by kvark** [comment]
I believe the end goal is to have a single WR instance anyway, that is managing multiple independent documents/scenes. In that case, WR will not need to have any built-in protection from multiple instances collision. However, in order to allow this to be patched on the Gecko side, WR does need to provide some way to make those `IdNamespace` different.

**Comment by glennw** [comment]
https://github.com/servo/webrender/pull/1882 has landed.
