### ISSUE TITLE
Some text has black boxes around the glyphs

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1839]
https://bugzilla.mozilla.org/show_bug.cgi?id=1407345

That bug has a [testcase](https://bug1407345.bmoattachments.org/attachment.cgi?id=8917075) which uses `mix-blend-mode`, but @Gankro tells me he has also seen this issue with 3d transforms.

<img width="186" alt="screen shot 2017-10-10 at 2 04 28 pm" src="https://user-images.githubusercontent.com/961291/31402439-f81f4a48-adc3-11e7-9056-ac377ea93197.png">

**Comment by Gankro** [comment]
Mine was https://bugzilla.mozilla.org/show_bug.cgi?id=1406179

```
data:text/html,<div style="perspective:1000px"><div style="transform-style: preserve-3d">hallo
```
![screen shot 2017-10-10 at 2 18 41 pm](https://user-images.githubusercontent.com/1136864/31403043-f3a3b6b4-adc5-11e7-8775-061e23ae7737.png)

**Comment by mstange** [comment]
After #1816, the testcase with mix-blend-mode now gets black boxes in both lines, not just in the second line.

**Comment by glennw** [comment]
OK, I can see the problem - we don't determine early enough that this run is on a transparent background and disable subpixel AA. Even though in the near future, we'll support that, I'm going to do the work to be able to determine earlier when a run is on a transparent background - because this is part of the planned work in #1774 anyway, that will be useful to have for several other reasons.

**Comment by glennw** [comment]
I added an interim fix in #1844.

**Comment by mstange** [comment]
This testcase still shows the issue in Firefox with an updated webrender. I'm not sure if Firefox actually forwards the CSS `isolation` property as an isolated WebRender stacking context.

**Comment by kvark** [comment]
Looks like we need a reftest for this

**Comment by gw3583** [comment]
The bugzilla bug for this is resolved fixed.
