### ISSUE TITLE
Poor GPU time on http://worrydream.com

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1840]
http://worrydream.com is ok with Firefox+webrender with regular window sizes but goes really slow once the window covers my full external HiDPI monitor, with GPU times around 80ms.

**Comment by glennw** [comment]
Profiling shows that in this page, every image has a rotation transform applied. Due to the way the legacy ```ps_image``` shader works, that means every image is going through the alpha pass. I'll work on switching the image shader to be a brush shader, which can then opt in to segment building. This should fix any performance issues on this page.

**Comment by gw3583** [comment]
This does seem reasonable now on my test machine - it gets to ~11ms GPU time worst case on a 4k display with an HD4600. @mstange could you confirm if this is OK on your test setup or still needs work?

**Comment by mstange** [comment]
This is excellent now: GPU times are around 6.5ms. That's quite an improvement over 80ms!
