### ISSUE TITLE
Missing sides on boxes on codesandbox.io

### ISSUE THREAD

**Issue by bogas04** [servo/webrender#2055]
I'm using WebRender on Nightly (OSX) and found a rendering issue while browsing on https://codesandbox.io. The sides of the boxes aren't getting filled with the background-color.

Refer to this tweet: https://twitter.com/bogas04/status/931450562410770432?s=17

**Comment by kvark** [comment]
Thanks for filing the issue! We seem to be improperly transforming 3d contexts here.

**Comment by Darkspirit** [comment]
mozregression --find-fix --bad 2017-11-17 --good 2018-01-15 --pref layers.acceleration.force-enabled:true gfx.webrender.enabled:true gfx.webrendest.enabled:true gfx.webrender.blob-images:true image.mem.shared:true layout.display-list.retain:false startup.homepage_welcome_url:"https://codesandbox.io/"
> 8:01.60 INFO: First good revision: 8ccb0e9d9bbeeed7d7e4474849debd7d21b65971
> 8:01.60 INFO: Last bad revision: c174ef283f5561aa3cf24b1d014b5f62dcd5ccd4
> 8:01.60 INFO: Pushlog:
> https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=c174ef283f5561aa3cf24b1d014b5f62dcd5ccd4&tochange=8ccb0e9d9bbeeed7d7e4474849debd7d21b65971

> da9b75fc0866	Kartikaya Gupta — [Bug 1426116](https://bugzilla.mozilla.org/show_bug.cgi?id=1426116) - Update webrender to commit a422f907be948b92bf5c7003a01f7744391a795e. r=jrmuizel

Fix range: https://github.com/servo/webrender/compare/1142dfc557c319119a5117450718c5b67a93cb9f...a422f907be948b92bf5c7003a01f7744391a795e

Possibly fixed by #2250.

Thank you! :)
