### ISSUE TITLE
Facebook uses more cpu with webrender than Chrome

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2123]
Running https://jrmuizel.github.io/webrender/facebook-refresh.html on MBP shows (42% usage child process, 60% usage parent process) vs (52% child, 11% GPU) in Chrome

**Comment by jrmuizel** [comment]
Of note is 60% vs 11%

**Comment by glennw** [comment]
I will investigate this today.

**Comment by glennw** [comment]
From an initial profile, I get:

![fb](https://user-images.githubusercontent.com/2350882/33347959-56558486-d4e0-11e7-9e4d-c5fa4e78f0b6.png)

This has ~5-8ms in DisplayList in Gecko, and ~3-4ms in RenderLayers.

![fb2](https://user-images.githubusercontent.com/2350882/33348009-77e4e54c-d4e0-11e7-922c-49c17b443ba0.png)

We're seeing particularly high CPU time in compositor (although this *might* be invalid profile numbers since vsync is enabled here). The render backend and display list IPC times also seem high.

I'll start by looking into the compositor CPU time result.

@jrmuizel Do those figures roughly match up with what you're seeing on this page (in terms of proportions inside Gecko and WR)?

**Comment by glennw** [comment]
OK, with vsync disabled (on Intel Linux, ```vblank_mode=0``` and ```layout.frame_rate``` set to 0), the compositor time is ~3ms.

All of these numbers are higher than ideal, but not unexpected given the known current CPU bottlenecks. I'll get some more detailed profiling info on what the hotspots are for us to target first.

**Comment by jrmuizel** [comment]
They possibly match. I had a look at profile from @emilio's machine and the
child side seemed reasonable except for a bad fallback case for input
type=file.

I'm more worried about the webrender side. I was seeing a lot of cpu time
in the renderer thread

**Comment by jrmuizel** [comment]
I'll post a profile later tonight that shows what I see

**Comment by glennw** [comment]
OK, I'll investigate the renderer time anyway - even if it is ~3 ms, that still seems really high.

**Comment by glennw** [comment]
There are a lot of draw calls occurring on this page. There's several planned improvements to help with this - most of them reliant on switching items over to be brush shaders that can batch together. Since there's a lot of optimizations that are blocked on this work - I'm going to start on those today. Porting rectangles and border corner/edge shaders to brush shaders should eliminate a lot of draw calls and batching overhead, and will also open up several other optimizations that are currently blocked.

**Comment by glennw** [comment]
https://github.com/servo/webrender/pull/2130 is a small win here - it drops the draw calls from 172 to 154, saving around 10% of the CPU time in the compositor thread. I'm going to continue investigating the batching on this site, as that still seems very high.

**Comment by jrmuizel** [comment]
Here's my profile: https://perfht.ml/2ieKFPw
Unfortunately the gecko profiler doesn't have a good way of distinguishing waiting vs working so this profile doesn't really show the same things as instruments.

**Comment by jrmuizel** [comment]
Breaking out the timing information in the profiler for webrender_bindings::bindings::wr_renderer_render vs GLContextCGL::SwapBuffers would be helpful. I can fix that.

**Comment by glennw** [comment]
One interesting thing I found (though unrelated to this issue) - there is a very large image that appears to be a single color:

alloc ImageDescriptor { format: BGRA8, width: 1887, height: 2081, stride: Some(7548), offset: 0, is_opaque: false }

Appears to be light grey.

It's probably worth finding out where that comes from in the display list and if it's redundant, because it could be costing quite a lot of GPU time and memory.

**Comment by glennw** [comment]
Oh, and it's marked as not opaque either - so that will definitely be costing performance. Perhaps it's an image mask covering the whole screen or something?

**Comment by pcwalton** [comment]
Something strange about this benchmark is that Chrome causes the WindowServer to use a ton of CPU, primarily in `CA::Render::Surface::decode()`. Is Chrome using Core Animation in some different way?

**Comment by gw3583** [comment]
This seems ok now.
