### ISSUE TITLE
[RFC] Remove "complex" radial gradient support?

### ISSUE THREAD

**Issue by glennw** [servo/webrender#2439]
In ```display_list.rs``` there are two methods for creating radial gradients.

```create_radial_gradient``` takes a center point, an (elliptical) radii, and a series of stops.

```create_complex_radial_gradient``` takes several more parameters (a start and end center, start and end radii, ratio_xy, stops etc).

As far as I can see, neither Gecko nor Servo ever use the complex radial gradient API. And from reading the CSS specification, I can't see the usefulness of the complex radial gradient API - it seems like the simple API should be able to express all radial gradients that CSS is able to.

So, I'd like to remove the complex radial gradient API - it will allow some quite significant optimizations to the radial gradient shader (and gradients in general).

Does this sound reasonable? Is anyone aware of a use for the complex radial gradient API? Is the Gecko + WR radial gradient integration complete?

**Comment by glennw** [comment]
cc @jrmuizel @lsalzman @staktrace @nical @kvark @mstange 

Apologies for the big CC list - I'm not sure who is best to answer this.

**Comment by lsalzman** [comment]
Looks like @eqrion added this in PR #1026. So he would be the best to ascertain what it was for and whether it is required anymore.

**Comment by eqrion** [comment]
My recollection is that complex radial gradient was the original radial gradient shader. I added the simpler one which can do all the things CSS gradients can do. The complex radial gradient shader can handle most (or all?) the things that SVG radial gradients need.

It shouldn’t be used in Gecko right now. So I don’t see a huge need to keep it around, would be easy to add it back if needed.

**Comment by glennw** [comment]
@eqrion @lsalzman From reading the issue linked, it sounds like we would only need all the extra params when natively rasterizing SVG radial gradients. I'll remove them at this stage, we can always add back later as you said. Thanks!

**Comment by mrobinson** [comment]
I've started working on this. It's a little bit tricky because it involves moving some code from the DisplayListBuilder into the DisplayListFlattener in order to prevent wrench from relying on the complex radial gradient support.

**Comment by mrobinson** [comment]
The main issue with removing the complex radial gradient support is that the `DisplayListBuilder` does quite a bit of pre-processing of gradient arguments and stops. Every processed gradient is stored in arguments equivalent to what Wrench recordings produce.

 * `start_center` and `end_center`: The non-complex radial gradient API only uses a single center and these values are affected at all by preprocessing. I've created #2534 which removes these two from the complex API.

* `start_radius` and `end_radius`: This is typically `radius.width * start_offset` and `radius.width * end_offset`. We should be able to eliminate these, except in the case of degenerate gradients the values used for `start_offset` and `end_offset` are no the same as the actual start and end offsets used in the stops array.

`ratio_xy`: It should be possible to eliminate this and just replace it with the radius from the original set of arguments.

Longer term, perhaps it makes sense to move normalization of stops and fixups for degenerate gradients out of the display list builder. The main difference would be that the stops would need to be fixed up during display list flattening instead of display list building, perhaps leading to extra copies.

**Comment by glennw** [comment]
Moving the stops normalization to the flattening seems like a good idea to me. If we moved them one step further, to ```prepare_prim_for_render()```, then they only get processed when gradients come on screen for the first time, which may reduce some of the up-front work on some pages. This is how text runs work - we only retrieve and process the glyphs the first time the text run becomes visible.
