### ISSUE TITLE
Large element with 2d transform disappears sometimes

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2531]
When scrolling up and down on [this testcase](https://bug1446129.bmoattachments.org/attachment.cgi?id=8959296), the blue box sometimes disappears.

Here's a recording of a frame where the element is missing: http://tests.themasta.com/webrender-transformed-large-box-disappears-capture.zip

**Comment by Darkspirit** [comment]
* [bug 1446129](https://bugzilla.mozilla.org/show_bug.cgi?id=1446129) (above comment) | Large element with transform disappears during scrolling
* [bug 1445034](https://bugzilla.mozilla.org/show_bug.cgi?id=1445034) | http://gifpaint.com/ canvas disappears when scrolling upwards

Regressed by: #2362

**Comment by glennw** [comment]
cc @nical - It seems unlikely that #2362 would cause this, but it seems like that is the regression range :)

**Comment by Darkspirit** [comment]
* [bug 1446626](https://bugzilla.mozilla.org/show_bug.cgi?id=1446626) | Redraw issues scrolling specific website with WebRender enabled ([Screencast](https://youtu.be/re5Rkk0LOoY))

**Comment by nical** [comment]
Looking at a renderdoc capture of the bug, the triangles for the missing element(s) are there and in the right place but they don't end-up affecting any pixel. Even when forcing the the alpha to be 1.0 in the vertex and fragment shaders nothing is drawn, so my best guess so far is that we are getting garbage input data causing the pixels to be discarded.
Maybe something in the async scene PR affected the ordering of gpu cache updates somehow.

As far as I can tell, disappearing elements always reappear as soon as we rebuild the scene.
It also looks look like (but harder to be sure), they don't necessarily disappear when building a scene (but rather at some point during a scroll frame).

**Comment by nical** [comment]
@kvark do you have any recommendation about ways to debug/check the state of the gpu cache to get an idea of whether something is fishy in there?

**Comment by nical** [comment]
Another note to self because I won't remember tomorrow:
It appears that the disappearing primitive first goes through the update_clip_task_for_brush code on a frame where things go well, and subsequent frames earlies out in the branch that checks that clips.is_empty() and combined_outer_rect == prim_screen_rect.
if I prevent it from going through update_clip_task_for_brush it renders properly. 
Wondering if there is some leftover state that makes it do the wrong thing (maybe something where it would get segmented at a certain scroll position and would not when we scroll up and then ends up in a weird state at certain scroll offset.

**Comment by nical** [comment]
Ok I can confirm that when we scroll down the transformed blue rect gets segmented (a single segment) while when we are at the top of the page the primitive is not segmented. If the scene is built when we are at the bottom of the page and we segment the primitive, when we go up we end up keeping the segment instead of taking the code path that we would have chosen if the primitive had its segment descriptor set to its initial value (`None`).
Remains to decide whether the segmented primitive should have been able to render properly in this configuration, or if it was incorrect to carry on with the segments and we should have reset the primitive at some point (not quite sure what would have been the trigger to reset the segments).

If it is the later we probably need a distinction between segmentation that happens during scene building (for example when separating border parts), and the segmentation that we do while building the frame (clipping stuff).

@glennw thoughts?
