### ISSUE TITLE
Display items with off-screen positions that are translated to be on-screen incorrectly culled out

### ISSUE THREAD

**Issue by pcwalton** [servo/webrender#262]
Test case:

    <!DOCTYPE html>
    <div style="transform: translateX(-2000px)">
        <div style="position: absolute; top: 0; left: 2000px;">X</div>
    </div>

This breaks http://apple.com/.

**Comment by daoshengmu** [comment]
I can help investigate. I notice the below test case is wrong as well. 

```
<div style="transform: translateX(0px)">
    <div style="position: absolute; top: 0; left: 0px;">X</div>
</div>
```

**Comment by daoshengmu** [comment]
I think I have fixed the first test case via this way at `frame::add_items_to_target()`:

```
let rect = info.world_transform.transform_rect(&item.rect
                  .translate(&info.offset_from_current_layer));
```

Because it forgets to append the world transform from it parent. I have checked http://apple.com/ that works well.

The test case of ```left: 0px;``` is another case that the letter `x` is clipped. Probably there is something wrong on the scissor test. I will follow up for this.

@pcwalton Do you think it is ok for me to send a PR?

**Comment by tschneidereit** [comment]
@daoshengmu, if you already have a patch that fixes the issue for you, it's best to just open a PR. If something's wrong about it, then that can be discussed in the PR itself instead of here. This way, you don't need to wait for a response here and then again in the PR after you opened it.

**Comment by glennw** [comment]
No longer an issue in WR2.
