### ISSUE TITLE
debug_font shader has compilation failures

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2808]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1460442

I think the debug_font shader is only compiled by the DebugRenderer, which only gets used in non-default scenarios (e.g. if a pref is flipped). So that probably accounts for the relatively low volume of crashes. But it happens on a variety of graphics cards so presumably it shouldn't be hard to reproduce and fix.

**Comment by kvark** [comment]
>  called `Result::unwrap()` on an `Err` value: Compilation("debug_font", "")

hm, so no actual error message is given?

**Comment by kvark** [comment]
The machine I got here is pretty close to one of the repro cases: also Win10, Rx 460 instead of Rx 480, the only suspect-able difference is an older driver (22.19.677.257 as opposed to 24.20.11001.5003 seen in the log). And it works (testing with `cargo run --features debugger --example basic`). Trying to update the driver to check if it's an upstream regression.

**Comment by kvark** [comment]
Hmm, can't repro with 24.20.11019.1004 either. Confirmed that the failing shader is built when running with this command line.
