### ISSUE TITLE
Why does webrender take nearly 100 MB of RAM when rendering text?

### ISSUE THREAD

**Issue by fasihrana** [servo/webrender#3222]
I've been working on a GUI framework with webrender as the rendering engine. I've noticed that the RAM consumption is about 100MB when I start rendering text. This happens on both Windows and Ubuntu. I understand that text rendering is quite complex and calculation intensive, but doesn't 100MB RAM seem a bit too much? Maybe I'm doing something?

You can find the code sample here: [fasihrana/skryn](https://github.com/fasihrana/skryn/tree/fontkitbranch).

With text rendering:
![alt text](https://i.imgur.com/YGDiTaM.png "with text rendering")

Without text rendering:
![alt text](https://i.imgur.com/T37WI6i.png "without text rendering")

The difference between both these runs is that for the run without text rendering I've commented out the following line:
[line 166: `map.insert(c, (gi[i], gd));`](https://github.com/fasihrana/skryn/blob/2e2e732b0214ee0a996e8c34ed3f1b451341352a/src/gui/font.rs#L166)

**Comment by gw3583** [comment]
This is *probably* caused by the lazy allocation of the texture atlas.

WR will only start allocating memory for the texture cache once an image / glyph is placed in it for the first time. Unfortunately, the texture cache is currently a large, fixed size. The downside is that there is an immediate jump to a large memory usage - but on the plus side, there generally won't be any further allocations made, even as you add thousands more glyphs / images.

There is some ongoing work by @bholley to make the texture cache start out much smaller, and grow as required, which should fix this.

**Comment by fasihrana** [comment]
Thanks for that explanation.

**Comment by gw3583** [comment]
The texture cache now starts very small and grows as required, so I think this will be resolved.
