### ISSUE TITLE
font-rs?

### ISSUE THREAD

**Issue by leeoniya** [servo/webrender#325]
see https://github.com/servo/servo/issues/12709

maybe i should have opened this here?

@glennw @pcwalton

**Comment by louisremi** [comment]
As far as I understand, font-rs is a CPU based font renderer. @evanw has developped a GPU based glyph renderer, see https://medium.com/@evanwallace/easy-scalable-text-rendering-on-the-gpu-c3f4d782c5ac#.iuglb1e5v Which, as is, seems patent encumbered though : https://www.google.com/patents/US20070097123 :-/

**Comment by brandf** [comment]
The loop/blinn technique from the patent is not the same as the stencil buffer technique that evanw describes in the medium article.

The stencil technique is similar to stencil shadows, which are used in many games, so I'd be surprised if it's encumbered.

**Comment by metajack** [comment]
webrender already renders glyphs on the CPU, so font-rs may work well. I believe the plan is to make the font support a trait so that it can use whatever is provided. In Servo's case this is currently freetype or Core Text, and we were planning on adding DirectWrite. However, it could make sense to replace rasterization with font-rs if that has enough features.

cc @vvuk

**Comment by glennw** [comment]
We'll probably want to either stick with the default platform rasterizer, or use a GPU-specific solution.
