### ISSUE TITLE
GL setup is busted on android emulator

### ISSUE THREAD

**Issue by jdm** [servo/webrender#3312]
When I run a debug servo build inside of the android emulator on macOS, I hit [this assertion](https://github.com/servo/webrender/blob/02387f7e5c77c415cfa232366c321d6f621cae28/webrender/src/device/gl.rs#L1011). The emulator emulates GLES in a way that does not claim to support BGRA, which prompted the original code that I wrote in https://github.com/servo/webrender/pull/2731.

**Comment by jdm** [comment]
cc @jamienicol

**Comment by jamienicol** [comment]
Ah, I see.

#3195 is actually what will have broken this. It seems to have lost the context of #2731: that we were knowingly using RGBA instead of BGRA for the external format in order for it to work at all, even if the colours are wrong. It made it so we have internalformat=RGBA and externalformat=BGRA. When I implemented #3239 I noticed that isn't going to work, because gles cannot swizzle during upload, so I added the assertion. But it would have been better to restore the previous behaviour.

We should remove the assertion, and then for gl.get_type == gles && !supports_bgra, we want to return internalformat=RGBA8, externalformat=RGBA
