### ISSUE TITLE
webrender does not build with stable rust

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#336]
We need this to able to put it in Gecko.

**Comment by emilio** [comment]
cc @nox, who did a tom of dependency work, how much work is needed for this?

**Comment by nox** [comment]
AFAICT the only thing needed is https://github.com/servo/ipc-channel/commit/0e11b11900e2f0a07ea10c92741d6aa1f3648bb3, but that comes with the serde bump too, which depends on bumping hyper otherwise we get a serde split in servo. I can also just put that on an v0.4.x branch in ipc-channel if we are that hurried. WR and WR_traits themselves don't use fancy unstable features by default.

**Comment by nox** [comment]
Also for Gecko we probably need an implementation of ipc-channel for Windows that actually work. Cc @metajack @vvuk.

**Comment by drawoc** [comment]
Current master (68824209) builds on stable rust (1.12) for me.

**Comment by nox** [comment]
Did you try on Windows?

**Comment by drawoc** [comment]
Uh, no. I'm on 64-bit linux. I thought it might be worth noting that it builds on stable on at least one platform. I wouldn't know about windows.

**Comment by nox** [comment]
Yes it's definitely good news!

**Comment by glennw** [comment]
@nox Should we close this bug now, since I think WR itself builds on stable (we could open bugs in upstream dependencies if we need to)?

**Comment by nox** [comment]
NOT TRUE ANYMORE WOOOOOOOOOOOOOOO
