### ISSUE TITLE
test hashbrown out for potential free perf wins

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#3363]
https://github.com/Amanieu/hashbrown

It's currently being tested out as a replacement for the std's current implementation: https://github.com/rust-lang/rust/pull/56241

This would be a nice to try out because it: 

* produces further data for the libs team to make an informed decision about std
* potentially give us free perf wins today (as opposed to maybe in a few months)
* may give us access to lower-level APIs which are normally locked up behind nightly-only feature gates (raw_entry)

**Comment by gw3583** [comment]
If this is API compatible with std HashMap, all that should be required is changing this line:

https://github.com/servo/webrender/blob/323b7ea140ba956af342e4f2660e67e04913e9fb/webrender/src/internal_types.rs#L27

And then doing some profiling.

**Comment by emilio** [comment]
With a few more re-triggers and tests that `-t all` doesn't include as suggested by @bholley:

 * No hashbrown: https://treeherder.mozilla.org/#/jobs?repo=try&revision=eaf9c509df544bc4a81809a4146ed44a9db414eb
 * Hashbrown: https://treeherder.mozilla.org/#/jobs?repo=try&revision=4b975a6356387bb144159693504231d5ad71f342

**Comment by Gankro** [comment]
Ah sadly, the out of tree copy requires a nightly feature to get a significant performance bump, due to unstable branch prediction hint intrinsics: https://github.com/Amanieu/hashbrown/blob/master/src/raw/mod.rs#L12-L25

**Comment by Gankro** [comment]
(Amanieu is suggesting the latest nightly has these intrinsics be harmful, looking into it)

**Comment by Gankro** [comment]
Yeah so on the latest(?) nightly the codegen without the nightly feature is perfectly good, and using these intrinsics regresses performance. Weird...

**Comment by bholley** [comment]
The memory win is probably more interesting for Stylo than for WebRender, since the former makes much heavier use of hashmaps and is more CPU-memory-intensive in general. However, Stylo currently uses a forked version of std::HashMap in order to get fallible allocation.

When I discussed this with @emilio, my recommendation was that the extra complexity of yet-another HashMap quirk wasn't worth it without measurable wins, and that we should wait for fallible allocation in std::HashMap and then unfork. Once we do that, we can either use HashBrown everywhere, or wait for it to end up in stdlib (which I seem to recall was being considered).

**Comment by gw3583** [comment]
Probably nothing further to do here right now - but we can reopen in the future if / when we decide to investigate this again?
