### ISSUE TITLE
How can I use surfman with webrender

### ISSUE THREAD

**Issue by Hankszhang** [servo/webrender#4000]
Hi  guys，I want to use surfman(as the GL context) and webrender (as the Render engine) to do some Rendering stuff，because surfman use ANGLE on Windows, which should achieve better robustness.
but all examples in webrender use glutin as the GL context, and Servo's implement is too complicated to understand,  so I don't know how to achieve that now, I need some help~

**Comment by kvark** [comment]
[Here is](https://github.com/servo/webrender/blob/41394e3d291ff744aaedb5601186e1eeb14db455/examples/common/boilerplate.rs#L144) where the examples initialize GL with function pointers. You'd just be getting the pointers from `surfman` instead of `glutin`.

Note also that `wrench` has "--angle" option.

**Comment by Hankszhang** [comment]
@kvark OK I'll try,  thanks
