### ISSUE TITLE
Panic when a stacking context has an invalid transform.

### ISSUE THREAD

**Issue by glennw** [servo/webrender#418]
If a transform matrix cannot be inverted, the webrender code will currently panic. Instead, it should detect this and not try to draw the stacking context.

**Comment by j3parker** [comment]
I can grab this. According to https://drafts.csswg.org/css-transforms/#transform-function-lists

> If a transform function causes the current transformation matrix (CTM) of an object to be non-invertible, the object and its content do not get displayed.

Would a reasonable implementation in the context of servo mean that the object doesn't show up in the display lists (similar to if it had `display: none`)?

**Comment by glennw** [comment]
It probably can be done in layout, however I think it's probably simpler to handle in WR. If we check in WR, it will also handle this case for any clients that aren't Servo.

This piece of code (https://github.com/servo/webrender/blob/master/webrender/src/tiling.rs#L1822) concatenates the full stacking context transform, and also marks stacking contexts as visible or not. I suspect all you need to do is check if the transform is invertible here, and if not, bail out of the function and mark the stacking context as not visible.

**Comment by j3parker** [comment]
Okay! I agree that putting the change in WR would be useful for other clients.

I originally asked because I had made the change you described and noticed that Servo still crashed because of hit-box stuff (i.e. that part of the DOM isn't rendered, but if you mouse in to the window then it panics.) I now think the correct solution is to do the check in multiple places. I'll PR the WR fix, open a related Servo issue this weekend.

**Comment by jdm** [comment]
This sounds like https://github.com/servo/servo/issues/13266 too.

**Comment by notriddle** [comment]
> It probably can be done in layout, however I think it's probably simpler to handle in WR. If we check in WR, it will also handle this case for any clients that aren't Servo.

Do non-Servo clients want that behavior?
