### ISSUE TITLE
Garbled rendering of transformed content

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#427]
http://people.mozilla.org/~jmuizelaar/servo/clipped-rotate.html renders badly on OS X

**Comment by glennw** [comment]
https://github.com/servo/webrender/pull/431 fixes the text being garbled. However, we need to add support for transformed clip rects to close this bug completely - I'll try to work on that in the next week or two.

**Comment by kvark** [comment]
Looking into this...

**Comment by kvark** [comment]
![garbled_text](https://cloud.githubusercontent.com/assets/107301/19691238/9459a80e-9aa1-11e6-9bd8-145fd0709600.png)

**Comment by kvark** [comment]
Interestingly, if I disable the `WR_FEATURE_TRANSFORM` paths in the `text_run` shaders, it renders better:
![text-comparison](https://cloud.githubusercontent.com/assets/107301/19693874/2b4e93c4-9aab-11e6-8e5f-766cc89b3d8c.png)
The layout seems to differ a bit with Firefox, and the font is smaller. Also, there are thin lines visible on the tile boundaries (I assume).

**Comment by kvark** [comment]
Got it almost fixed now with `WR_FEATURE_TRANSFORM`:
![textrun-update](https://cloud.githubusercontent.com/assets/107301/19819497/f46146b6-9d22-11e6-894a-69642d085756.png)

There is some stuff missing at the end of the lines, not sure if because of rendering or not. Will investigate and file a PR for what I got regardless.
