### ISSUE TITLE
Reduce unsafe code in `rasterize_glyph()`

### ISSUE THREAD

**Issue by kvark** [servo/webrender#515]
The method has a large `unsafe{}` block, which can be split into multiple smaller ones.

**Comment by hgallagher1993** [comment]
Ya I'll have a go at it

**Comment by emilio** [comment]
Neat, let us know if you need any help!

**Comment by hgallagher1993** [comment]
Will do :+1: Be a couple of days before I start it though, some final year project stuff to get out of the way first

**Comment by hgallagher1993** [comment]
Only just got round to this now for a few different reasons but anyway, the changes are made and all looks ok but what exactly is the process for making a pull request? Is it the same [as the Servo process](https://github.com/servo/servo/wiki/Github-workflow) except instead of servo/servo it's servo/webrender?

**Comment by emilio** [comment]
Yeah, it's pretty much the standard workflow.

Thanks for working on it! :)

**Comment by glennw** [comment]
Fixed in https://github.com/servo/webrender/pull/757
