### ISSUE TITLE
Support using WebRender without IPC

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#558]
It looks like we're going to be using Gecko IPC with WebRender instead of the Servo IPC. In this situation we don't want to be eating the overhead of an additional IPC serialization/copy.

**Comment by glennw** [comment]
@jrmuizel I have been planning for a while to add support for using an in-process normal channel, which could be used for messages sent between the compositor thread and webrender as a performance win. I think this should also cover your use case in this issue?

**Comment by glennw** [comment]
I think the API object would be basically the same, but when creating it, you'd pass a parameter choosing whether this API objects communicates over IPC or normal rust channels. Then the gecko bindings wouldn't change much at all - they'd just select a different API type at init time.

**Comment by metajack** [comment]
@glennw I have often thought the best way to do this is to make the IpcChannel stuff collapse to a normal Rust channel when used in-process.

**Comment by glennw** [comment]
@metajack Interesting idea! It might be good to have it as an optional cargo feature in WR though, so users of the library that don't use it can remove the ipc-channel dependency altogether.

**Comment by jrmuizel** [comment]
Yes, this approach sounds like it would be fine place to start.

**Comment by jrmuizel** [comment]
and avoiding the ipc-channel dependency would be nice.

**Comment by kvark** [comment]
Let me share a bit of early gfx-rs history that seems related to the problem. When we just started, we had 3 threads and 2 thread boundaries between them. One layer quickly became out of scope, and we had a similar setup to WR, with a difference that the other thread owned the context.

Of course, we realized then that not all clients want to have a different thread, and it introduces the complexity of debugging the system. So we re-architectured the code to leave that decision up to the user: one layer constructs command buffers, they are sendable objects, and another layer consumes them. If the user wants to own the context in a different thread, they are free to do it, then send/sync the command buffers for consumption.

Thus, the follow up question is: can we, instead of deciding between IPC/thread boundary for WR internals, leave that decision up to the client? I realize that WR story is different, and you don't want the client to know or have any access to `RenderBackend`. Just thought this parallel is worth a draw.
