### ISSUE TITLE
struct Scene doesn't support removing pipelines

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#691]
The HashMaps in here will just accumulate pipeline forever.

**Comment by akiselev** [comment]
Should this be fixed with a simple remove_pipeline() method on Scene or are there plans to support automated culling? What happens if a pipeline is in the heirarchy of the root stacking context when it is removed from the HashMap? How is GPU memory for a pipeline deallocated and does Scene even care or does it have to be done separately? (Haven't had time yet to dive into those details)

I'm working to implement the needed functionality for my own project but I'm using webrender outside of Servo so I don't know how high level the API should be for a PR. I'm guessing Servo will have its own implementation for tracking pipelines and freeing them but it might make sense to add some basic culling function to Scene that removes any pipeline not referenced in the root stacking context heirarchy or a function to remove all pipelines starting from a root pipeline.

**Comment by jrmuizel** [comment]
I think a simple remove_pipeline() is the best place to start. Once we have that we iterate on any improvements.

For now, we can probably just panic if the pipeline is missing (I think that's what happens today).
