### ISSUE TITLE
Implement preserve-3d

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#739]
The basic plan is to use a bsp tree to do plane-splitting like Gecko does.

It probably makes the most sense for this work to wait for the work in #742

**Comment by kvark** [comment]
Me and @mrobinson are interested to implement this.

**Comment by kvark** [comment]
Got https://github.com/kvark/plane-split, going to try hooking it up to WR next.

**Comment by jrmuizel** [comment]
The license should probably at least be dual with MPL2

**Comment by kvark** [comment]
Some observations from looking into this:
  1. when "preserve3d" is active for a sub-tree of the document, the elements are supposed to naturally be ordered by depth on a per-pixel level. It can have children that are "flat", not sure if we can support it from the start or implement as a follow-up.
  2. plane splitting is one of the ways to draw intersecting semi-transparent objects, it is viable on the way because most of the things are planes and thus can be trivially split
  3. we could have used the depth buffer for opaque objects, but that conflicts with the current approach. Thus, we need to split all the planes (including opaque ones) and assign the produced ordering to Z indices that are currently obtained from the original primitive order.
  4. when 2 planes intersect, we should only need to split one of them to avoid intersection (not both), and then return the draw order
  5. splitting can be done incrementally: we can have a splitter object that gets mutated each time we add a plane to it, this function returns the split plane and ordering info

**Comment by glennw** [comment]
preserve-3d support has merged. Let's close this and open new issues for any specific bugs / missing features.
