### ISSUE TITLE
Enable IRC bot

### ISSUE THREAD

**Issue by nox** [servo/webrender#849]
Issues filed here don't get advertised on #servo.

**Comment by emilio** [comment]
See also https://github.com/servo/rust-bindgen/issues/375#issuecomment-269927296, I believe the bot is enabled in this repo too.

**Comment by glennw** [comment]
cc @metajack @larsbergstrom @edunham We do seem to see PRs being opened / closed in IRC, but not the same for issues.

**Comment by edunham** [comment]
It's supposed to be enabled. I deleted and recreated it and it still doesn't work... It's configured identically to servo/servo. For added confusion, "test payload" button works on this repo's hook but does not work on the servo/servo one. I have contacted GitHub support to get their advice on why the two identically configured repos are behaving differently, since there's nothing about IRC service integration debugging in the actual GitHub help.

**Comment by metajack** [comment]
I got a response from GitHub support. You can't turn on issues support without using the API. There's no web interface for controlling that. They recomended this curl script:
`curl -v -X PATCH -H "Authorization: token OAUTH-TOKEN" https://api.github.com/repos/servo/webrender/hooks/:id --data '{"add_events":["issues"]}'`

**Comment by metajack** [comment]
This repo is fixed.

**Comment by emilio** [comment]
Could someone with the proper permissions do the same for servo/rust-bindgen?

**Comment by metajack** [comment]
Done.

**Comment by emilio** [comment]
Thanks! :)
