### ISSUE TITLE
Change RGBA format images to be interpreted as premultiplied alpha

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#889]
Currently it seems like webrender assumes that RGBA images are not premultiplied. This is an inconvenient assumption because nearly all of the images that Gecko produces are premultiplied. Servo also seems to assume premultiplied in some cases https://github.com/servo/servo/issues/15578. The easiest thing to do is probably just for Servo to premultiply png images before sending them to webrender.

**Comment by jamienicol** [comment]
I can have a look at this.

**Comment by glennw** [comment]
Great! I think we should have the Servo-side patches ready to go before we land this in WR, so we can do a full test run and make sure everything passes. Let me know if you need any help with that part.

**Comment by jrmuizel** [comment]
Here's a servo side patch
```patch
diff --git a/components/net_traits/image/base.rs b/components/net_traits/image/base.rs
index a6bc08c..6fa6075 100644
--- a/components/net_traits/image/base.rs
+++ b/components/net_traits/image/base.rs
@@ -38,23 +38,24 @@ pub struct ImageMetadata {
 // FIXME: Images must not be copied every frame. Instead we should atomically
 // reference count them.
 
 // TODO(pcwalton): Speed up with SIMD, or better yet, find some way to not do this.
 fn byte_swap_and_premultiply(data: &mut [u8]) {
     let length = data.len();
 
     for i in (0..length).step_by(4) {
-        let r = data[i + 2];
-        let g = data[i + 1];
-        let b = data[i + 0];
-
-        data[i + 0] = r;
-        data[i + 1] = g;
-        data[i + 2] = b;
+        let a = data[i + 3] as u32;
+        let r = data[i + 2] as u32;
+        let g = data[i + 1] as u32;
+        let b = data[i + 0] as u32;
+
+        data[i + 0] = ((r * a + 128)/255) as u8;
+        data[i + 1] = ((g * a + 128)/255) as u8;
+        data[i + 2] = ((b * a + 128)/255) as u8;
     }
 }
 
 pub fn load_from_memory(buffer: &[u8]) -> Option<Image> {
     if buffer.is_empty() {
         return None;
     }
 
```

**Comment by jamienicol** [comment]
Sorry I've been a bit quiet on this. @jrmuizel's patch fixes the few test failures there were, but it causes some more:
* tests/wpt/web-platform-tests/2dcontext/compositing/ - because the data was already being premultiplied in canvasrenderingcontext2d draw_image(), so it is now being premultiplied twice.
* tests/wpt/web-platform-tests/webgl/conformance-1.0.3/conformance/textures/gl-teximage.html - because it asserts that the texture data has not been premultiplied.

Canvas is easily fixable but I'm not sure what we want to do for webgl. WebGLRenderingContext expects the data it gets from the image cache to be unpremultiplied.

I think our options are:
* Servo's image cache data remains unpremultiplied. Add an API to webrender to accept unpremultiplied image data, which it would then premultiply itself internally.
* Servo's image cache data remains unpremultiplied. Premultiply a _copy_ of the data before sending it to webrender.
* Servo's image cache data switches to premultiplied, as per Jeff's patch. Then unpremultiply data before uploading to webgl.

1 or 2 seem okay to me. 3 seems like it would be a bit of a hack. @glennw, @jrmuizel ?

**Comment by jamienicol** [comment]
We already copy the data before sending it to webrender, so the second option seems the best. Will have a patch soon.

**Comment by jrmuizel** [comment]
Yes. I like option 2 the best for now as well.

**Comment by kvark** [comment]
There is also 4) upload the image as is to GPU, together with a "premultiplied" flag, then handle the pre-multiplication by the shaders
