### ISSUE TITLE
Hardware YUV image handling

### ISSUE THREAD

**Issue by kvark** [servo/webrender#956]
ARM Mali GPU has built-in support for working with YUV surfaces. See:
https://www.khronos.org/registry/OpenGL/extensions/OES/OES_EGL_image_external.txt

This is somewhat theoretical, but we should keep that extension on our radar as a potential power saver on mobile devices.

**Comment by nical** [comment]
For reference, Gecko also uses the image_external extension in some cases, probably because certain video decoders will produce this texture target and we have to be able to consume it. So we might need this not only as an optimization but also in order to ship on some platforms (I don't know exactly which platform/decoder configuration requires it).

**Comment by nical** [comment]
Fixed in https://github.com/servo/webrender/commit/06d73765cfded5c06c0e9d988afa6aca822d3b61
