### ISSUE TITLE
Intermittent crash with “failed to fill whole buffer”

### ISSUE THREAD

**Issue by SimonSapin** [servo/webrender#991]
Many intermittent test failures on Servo’s CI have in comment this error message: https://github.com/servo/servo/issues/14323.

The backtraces have `webrender::render_backend::RenderBackend::run` just before `core::result::unwrap_failed`. [That method](https://github.com/servo/webrender/blob/44465e785460528a0ee64b29e3b9282d8f6a314f/webrender/src/render_backend.rs#L112-L424) calls `std::io::Read::read_exact` which [does produce](https://github.com/rust-lang/rust/blob/bfc49b1092512aee4fe3d1348c3250fcdc8978d3/src/libstd/io/mod.rs#L627-L629) “failed to fill whole buffer” errors when the input is shorter than expected. In this case the input is `auxiliary_data`, obtained from `self.payload_rx.recv().unwrap()`. With IPC enabled (which I think is the case for Servo), `self.payload_rx` is a `ipc_channel::ipc::IpcBytesReceiver`, whose `recv` method returns `Result<Vec<u8>, _>`. But since `ipc_channel` has no documentation, I don’t know what length that vector is supposed to have. Does `recv` return exactly one vector for each corresponding `IpcBytesSender::send` call, or is this a byte stream that can be fragmented at any point? Anyway, somehow this vector is sometimes shorter than WebRender expects.

**Comment by SimonSapin** [comment]
CC @pcwalton for `IpcBytesReceiver::recv` semantics.

**Comment by pcwalton** [comment]
It should be returning exactly one vetcor for every corresponding `IpcBytesSender::send()` call. If not, it's a bug in ipc-channel.

**Comment by pcwalton** [comment]
Filed https://github.com/servo/ipc-channel/issues/160.

**Comment by SimonSapin** [comment]
This could be either that, or a bug in WebRender: the expected vector lengths are `display_list_descriptor.size()` and `auxiliary_lists_descriptor.size()`, and these descriptors are part of `ApiMsg::SetRootDisplayList`. Maybe the sender is buggy and sends a message that doesn’t match what is sent in the bytes channel?

**Comment by antrik** [comment]
A bit of a long shot: but is it possible by any chance that a single `Renderer` -- and thus a single `auxillary_tx` AIUI -- is used by multiple `LayoutThread`s?...

(That would be very bad, since it would mean the `epoch` is not unique I believe, thus causing all kinds of funny races...)

**Comment by jdm** [comment]
There is a single Renderer used by multiple LayoutThreads, yes. We create one Renderer per Browser (https://dxr.mozilla.org/servo/rev/449758ef5dd399f7e1a5a9550dcdd614056cee9e/components/servo/lib.rs#179-191) and clone the RenderApiSender value for each layout thread spawned from the same constellation.

**Comment by emilio** [comment]
So that seems quite likely, thanks for digging into it @antrik!

So mainly `set_root_display_list` is called from multiple layout threads, which seems dubious, and it sends _two_ messages, which don't necessarily need to be ordered (someone could send a message in between).

Those two messages are the `SetRootDisplayList` message, and the `Payload`.

So apart from the epoch thing that @antrik pointed out, it means that things can get out of sync pretty easily...

It seems dubious to me that the layout thread in the first place is setting the root pipeline, given that pipeline doesn't necessarily need to be displayed...

**Comment by emilio** [comment]
So we could add an explicit synchronization API to WR, or (ideally) we could fix servo to actually only render the top-level page, and send the stuff to the render back-end from the constellation instead of the layout thread.

That means, also, that we could move the IPC boundary off-webrender I think (the renderer lives in the constellation process), which will simplify things also for Gecko, is that right @glennw?

**Comment by SimonSapin** [comment]
CC @nical, it sounds like moving the IPC boundary would be relevant to you.

**Comment by emilio** [comment]
Actually as @glennw pointed out, we should probably just check the pipeline id + the epoch. Let's see if that fixes the intermittents, or we need to add more synchronization between those messages.

**Comment by emilio** [comment]
Relevant IRC discussion at http://logs.glob.uno/?c=mozilla%23servo&s=2+Apr+2017&e=2+Apr+2017#c643593.

Turns out we already have all that `leftover_auxiliary_data` to deal with the synchronization, the problem was exclusively the epoch mismatch problems @antrik pointed out.

I'm going to fix that for now, but we should also consider moving all the IPC complexity into Servo, and leave WR IPC-free. (I believe @staktrace could be happy about that too :P).
